#!/bin/bash
# ============================================================
# Script: webrtc-install.sh
# Purpose: Complete installation of all WebRTC infrastructure
# OS: Ubuntu 22.04 / 24.04 LTS
# Usage: sudo bash scripts/unix/webrtc-install.sh
#
# This script installs and configures:
#   1. System packages (curl, openssl, etc.)
#   2. coturn (TURN/STUN server for P2P calls)
#   3. Docker & Docker Compose
#   4. SRS Media Server (SFU for group calls)
#   5. Nginx reverse proxy
#   6. Let's Encrypt SSL certificates
#   7. UFW firewall rules
#   8. Fail2Ban intrusion prevention
#   9. Systemd service files
#
# IMPORTANT: Run this script on a fresh Ubuntu 22.04 server.
#            It will modify system configuration.
#
# Before running, set these variables:
#   - YOUR_DOMAIN (e.g., webrtc.yourdomain.com)
#   - YOUR_EMAIL  (for Let's Encrypt notifications)
# ============================================================

set -e  # Exit immediately on any error

# ==================== CONFIGURATION ====================
# CHANGE THESE VALUES before running the script!

# Your domain name (must have DNS A record pointing to this server)
YOUR_DOMAIN="${YOUR_DOMAIN:-webrtc.yourdomain.com}"

# Your email (for SSL certificate expiry notifications)
YOUR_EMAIL="${YOUR_EMAIL:-admin@yourdomain.com}"

# Auto-detect server's public IP address
SERVER_IP=$(curl -sf ifconfig.me || curl -sf icanhazip.com)

# Generate a random TURN authentication secret
TURN_SECRET=$(openssl rand -hex 32)

# ==================== COLOR CODES ====================
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

# ==================== HELPER FUNCTIONS ====================

log_step() {
    echo ""
    echo -e "${CYAN}${BOLD}━━━ Step $1: $2 ━━━${NC}"
    echo ""
}

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[OK]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

# ==================== PRE-FLIGHT CHECKS ====================

echo "============================================================"
echo "  Meow Meow — WebRTC Infrastructure Installer"
echo "============================================================"
echo ""
echo "  Server IP:    $SERVER_IP"
echo "  Domain:       $YOUR_DOMAIN"
echo "  Email:        $YOUR_EMAIL"
echo "  TURN Secret:  ${TURN_SECRET:0:16}... (truncated)"
echo ""

# Check we're running as root
if [ "$EUID" -ne 0 ]; then
    log_error "Please run this script as root (sudo)"
    exit 1
fi

# Check Ubuntu version
UBUNTU_VERSION=$(lsb_release -rs 2>/dev/null || echo "unknown")
log_info "Ubuntu version: $UBUNTU_VERSION"

if [[ "$UBUNTU_VERSION" != "22.04" && "$UBUNTU_VERSION" != "24.04" ]]; then
    log_warn "This script is tested on Ubuntu 22.04/24.04. Your version: $UBUNTU_VERSION"
fi

echo ""
read -p "Continue with installation? (y/N): " CONFIRM
if [[ "$CONFIRM" != "y" && "$CONFIRM" != "Y" ]]; then
    echo "Installation cancelled."
    exit 0
fi

# ==================== STEP 1: SYSTEM UPDATE ====================

log_step "1/9" "Updating system packages"

# Update package lists to get latest versions
apt update

# Upgrade all installed packages to latest versions
# -y flag auto-confirms all prompts
apt upgrade -y

# Install essential tools
# curl: For downloading files and making HTTP requests
# openssl: For generating secrets and SSL operations
# software-properties-common: For managing apt repositories
# python3: For JSON parsing in scripts
# stun-client: For testing STUN server connectivity
apt install -y \
    curl \
    openssl \
    software-properties-common \
    python3 \
    stun-client \
    net-tools \
    htop \
    vnstat

log_success "System packages updated"

# ==================== STEP 2: INSTALL COTURN ====================

log_step "2/9" "Installing coturn TURN/STUN server"

# Install coturn package
apt install -y coturn

# Enable coturn to run as a system service
# By default it's disabled for safety
sed -i 's/#TURNSERVER_ENABLED=1/TURNSERVER_ENABLED=1/' /etc/default/coturn

# Create coturn configuration
# See docs/WEBRTC-DEPLOYMENT-GUIDE.md Section 4 for detailed explanation
cat > /etc/turnserver.conf << TURNCONF
# ============================================================
# coturn Configuration — Auto-generated by webrtc-install.sh
# Generated: $(date '+%Y-%m-%d %H:%M:%S')
# ============================================================

# Network
listening-port=3478
tls-listening-port=5349
external-ip=$SERVER_IP
min-port=49152
max-port=65535

# Authentication
realm=$YOUR_DOMAIN
lt-cred-mech
use-auth-secret
static-auth-secret=$TURN_SECRET

# Security
fingerprint
no-multicast-peers
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=192.168.0.0-192.168.255.255

# Performance
total-quota=128000000
max-bps=300000
max-allocations=2000

# Logging
log-file=/var/log/turnserver/turnserver.log
no-stdout-log
TURNCONF

# Create log directory with correct permissions
mkdir -p /var/log/turnserver
chown turnserver:turnserver /var/log/turnserver

# Start coturn
systemctl restart coturn
systemctl enable coturn

# Verify
if systemctl is-active --quiet coturn; then
    log_success "coturn installed and running"
else
    log_error "coturn failed to start — check: journalctl -u coturn"
fi

# ==================== STEP 3: INSTALL DOCKER ====================

log_step "3/9" "Installing Docker"

# Remove old versions
apt remove -y docker docker-engine docker.io containerd runc 2>/dev/null || true

# Add Docker's GPG key
mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
    gpg --dearmor -o /etc/apt/keyrings/docker.gpg

# Add Docker repository
echo "deb [arch=$(dpkg --print-architecture) \
    signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list

# Install Docker
apt update
apt install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

# Install standalone docker-compose
curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" \
    -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

# Start Docker
systemctl start docker
systemctl enable docker

log_success "Docker installed: $(docker --version)"

# ==================== STEP 4: DEPLOY SRS ====================

log_step "4/9" "Deploying SRS Media Server"

# Create SRS directories
mkdir -p /opt/srs/conf /opt/srs/logs

# Create SRS configuration
cat > /opt/srs/conf/srs.conf << 'SRSCONF'
listen              1935;
max_connections     10000;
daemon              off;
srs_log_tank        console;
srs_log_level       warn;

http_api {
    enabled         on;
    listen          1985;
    crossdomain     on;
}

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

rtc_server {
    enabled         on;
    listen          8000;
    candidate       *;
}

vhost __defaultVhost__ {
    rtc {
        enabled     on;
        rtmp_to_rtc on;
        rtc_to_rtmp on;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
}
SRSCONF

# Create Docker Compose file
cat > /opt/srs/docker-compose.yml << 'COMPOSE'
version: '3.8'
services:
  srs:
    image: ossrs/srs:5
    container_name: srs-server
    restart: unless-stopped
    ports:
      - "1935:1935"
      - "1985:1985"
      - "8080:8080"
      - "8000:8000/udp"
    volumes:
      - ./conf/srs.conf:/usr/local/srs/conf/srs.conf
      - ./logs:/usr/local/srs/objs
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1985/api/v1/versions"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
COMPOSE

# Start SRS
cd /opt/srs
docker-compose up -d

# Wait and verify
sleep 5
if curl -sf http://localhost:1985/api/v1/versions > /dev/null 2>&1; then
    log_success "SRS deployed and running"
else
    log_error "SRS deployment failed — check: docker logs srs-server"
fi

# ==================== STEP 5: CREATE SYSTEMD SERVICE ====================

log_step "5/9" "Creating systemd service for SRS"

cat > /etc/systemd/system/srs.service << 'SERVICE'
[Unit]
Description=SRS WebRTC Media Server (Docker)
After=docker.service
Requires=docker.service

[Service]
Type=simple
Restart=always
RestartSec=10
WorkingDirectory=/opt/srs
ExecStartPre=-/usr/bin/docker-compose down
ExecStart=/usr/bin/docker-compose up
ExecStop=/usr/bin/docker-compose down
TimeoutStopSec=30

[Install]
WantedBy=multi-user.target
SERVICE

systemctl daemon-reload
systemctl enable srs

log_success "SRS systemd service created"

# ==================== STEP 6: INSTALL NGINX ====================

log_step "6/9" "Installing Nginx"

apt install -y nginx

log_success "Nginx installed"

# ==================== STEP 7: SSL CERTIFICATES ====================

log_step "7/9" "Setting up SSL certificates"

apt install -y certbot python3-certbot-nginx

# Only attempt SSL if domain resolves to this server
DOMAIN_IP=$(dig +short "$YOUR_DOMAIN" 2>/dev/null | head -1)
if [ "$DOMAIN_IP" = "$SERVER_IP" ]; then
    certbot --nginx -d "$YOUR_DOMAIN" --non-interactive --agree-tos -m "$YOUR_EMAIL"
    log_success "SSL certificate obtained for $YOUR_DOMAIN"
else
    log_warn "Domain $YOUR_DOMAIN does not resolve to $SERVER_IP (got: $DOMAIN_IP)"
    log_warn "Skipping SSL setup. Configure DNS first, then run:"
    log_warn "  sudo certbot --nginx -d $YOUR_DOMAIN"
fi

# ==================== STEP 8: FIREWALL ====================

log_step "8/9" "Configuring firewall"

ufw --force enable
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw allow 3478/tcp
ufw allow 3478/udp
ufw allow 5349/tcp
ufw allow 49152:65535/udp
ufw allow 1935/tcp
ufw allow 1985/tcp
ufw allow 8080/tcp
ufw allow 8000/udp

log_success "Firewall configured"

# ==================== STEP 9: FAIL2BAN ====================

log_step "9/9" "Installing Fail2Ban"

apt install -y fail2ban

cat > /etc/fail2ban/jail.local << 'F2B'
[DEFAULT]
bantime = 3600
findtime = 600
maxretry = 5

[sshd]
enabled = true
port = 22
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
F2B

systemctl enable fail2ban
systemctl start fail2ban

log_success "Fail2Ban installed"

# ==================== INSTALLATION COMPLETE ====================

echo ""
echo "============================================================"
echo -e "  ${GREEN}${BOLD}Installation Complete!${NC}"
echo "============================================================"
echo ""
echo "  Server IP:     $SERVER_IP"
echo "  Domain:        $YOUR_DOMAIN"
echo "  TURN Secret:   $TURN_SECRET"
echo ""
echo "  ┌─────────────────────────────────────────────────────┐"
echo "  │  IMPORTANT: Save your TURN Secret!                  │"
echo "  │  You need it for Supabase Edge Function secrets:    │"
echo "  │                                                      │"
echo "  │  TURN_SECRET = $TURN_SECRET"
echo "  │  SRS_API_URL = https://$YOUR_DOMAIN"
echo "  │  SRS_RTC_URL = https://$YOUR_DOMAIN/rtc/v1"
echo "  │                                                      │"
echo "  └─────────────────────────────────────────────────────┘"
echo ""
echo "  Management Commands:"
echo "    Start:   sudo bash scripts/unix/webrtc-start.sh"
echo "    Stop:    sudo bash scripts/unix/webrtc-stop.sh"
echo "    Restart: sudo bash scripts/unix/webrtc-restart.sh"
echo "    Status:  sudo bash scripts/unix/webrtc-status.sh"
echo "    Monitor: sudo bash scripts/unix/webrtc-monitor.sh"
echo ""
echo "============================================================"

# Save installation details to a file
cat > /opt/srs/install-details.txt << DETAILS
Meow Meow WebRTC Infrastructure — Installation Details
Generated: $(date)

Server IP: $SERVER_IP
Domain: $YOUR_DOMAIN
TURN Secret: $TURN_SECRET

Supabase Secrets to configure:
  TURN_SECRET = $TURN_SECRET
  SRS_API_URL = https://$YOUR_DOMAIN
  SRS_RTC_URL = https://$YOUR_DOMAIN/rtc/v1
DETAILS

log_success "Installation details saved to /opt/srs/install-details.txt"
