-- Create sample_men table
CREATE TABLE public.sample_men (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  age integer NOT NULL DEFAULT 25,
  country text NOT NULL,
  language text NOT NULL,
  bio text,
  photo_url text,
  is_active boolean NOT NULL DEFAULT true,
  is_online boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Create sample_women table
CREATE TABLE public.sample_women (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  age integer NOT NULL DEFAULT 25,
  country text NOT NULL,
  language text NOT NULL,
  bio text,
  photo_url text,
  is_active boolean NOT NULL DEFAULT true,
  is_online boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.sample_men ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sample_women ENABLE ROW LEVEL SECURITY;

-- RLS Policies for sample_men
CREATE POLICY "Admins can manage sample men" ON public.sample_men
  FOR ALL USING (has_role(auth.uid(), 'admin'));

CREATE POLICY "Anyone can view active sample men" ON public.sample_men
  FOR SELECT USING (is_active = true);

-- RLS Policies for sample_women
CREATE POLICY "Admins can manage sample women" ON public.sample_women
  FOR ALL USING (has_role(auth.uid(), 'admin'));

CREATE POLICY "Anyone can view active sample women" ON public.sample_women
  FOR SELECT USING (is_active = true);

-- Create indexes for better query performance
CREATE INDEX idx_sample_men_language ON public.sample_men(language);
CREATE INDEX idx_sample_men_active ON public.sample_men(is_active);
CREATE INDEX idx_sample_women_language ON public.sample_women(language);
CREATE INDEX idx_sample_women_active ON public.sample_women(is_active);

-- Insert sample men for all major languages (10 per language)
INSERT INTO public.sample_men (name, age, country, language, bio) VALUES
-- Hindi
('Aarav Sharma', 25, 'India', 'Hindi', 'Friendly chat partner'),
('Vihaan Kumar', 28, 'India', 'Hindi', 'Love conversations'),
('Aditya Singh', 26, 'India', 'Hindi', 'Here to connect'),
('Arjun Patel', 30, 'India', 'Hindi', 'Enjoy meaningful talks'),
('Reyansh Gupta', 24, 'India', 'Hindi', 'Looking for friends'),
('Ayaan Verma', 27, 'India', 'Hindi', 'Music enthusiast'),
('Krishna Joshi', 29, 'India', 'Hindi', 'Travel lover'),
('Ishaan Rao', 26, 'India', 'Hindi', 'Tech professional'),
('Shaurya Mishra', 25, 'India', 'Hindi', 'Sports fan'),
('Atharv Reddy', 28, 'India', 'Hindi', 'Book reader'),
-- Bengali
('Aritra Das', 26, 'India', 'Bengali', 'Cultural enthusiast'),
('Ayan Banerjee', 28, 'India', 'Bengali', 'Poetry lover'),
('Soham Ghosh', 25, 'India', 'Bengali', 'Art appreciator'),
('Rishav Sen', 27, 'India', 'Bengali', 'Music composer'),
('Anirban Bose', 30, 'India', 'Bengali', 'Writer at heart'),
('Sourav Mukherjee', 24, 'India', 'Bengali', 'Film buff'),
('Debojyoti Roy', 29, 'India', 'Bengali', 'History lover'),
('Arnab Chatterjee', 26, 'India', 'Bengali', 'Science geek'),
('Subhrajit Dey', 28, 'India', 'Bengali', 'Sports enthusiast'),
('Pritam Kar', 25, 'India', 'Bengali', 'Nature lover'),
-- Tamil
('Arun Kumar', 27, 'India', 'Tamil', 'Tech professional'),
('Karthik Rajan', 25, 'India', 'Tamil', 'Music lover'),
('Surya Prakash', 28, 'India', 'Tamil', 'Film enthusiast'),
('Vijay Anand', 26, 'India', 'Tamil', 'Sports fan'),
('Pradeep Selvam', 30, 'India', 'Tamil', 'Travel enthusiast'),
('Mohan Raja', 24, 'India', 'Tamil', 'Food lover'),
('Ganesh Venkat', 29, 'India', 'Tamil', 'Art collector'),
('Senthil Murugan', 26, 'India', 'Tamil', 'Book reader'),
('Rajesh Sundaram', 28, 'India', 'Tamil', 'Nature explorer'),
('Dinesh Babu', 25, 'India', 'Tamil', 'Photography buff'),
-- Telugu
('Ravi Teja', 26, 'India', 'Telugu', 'Cinema enthusiast'),
('Venkat Rao', 28, 'India', 'Telugu', 'Tech lover'),
('Srinivas Reddy', 25, 'India', 'Telugu', 'Music fan'),
('Naresh Kumar', 27, 'India', 'Telugu', 'Sports player'),
('Prasad Varma', 30, 'India', 'Telugu', 'History buff'),
('Suresh Babu', 24, 'India', 'Telugu', 'Travel lover'),
('Mahesh Chandra', 29, 'India', 'Telugu', 'Food explorer'),
('Ramesh Goud', 26, 'India', 'Telugu', 'Art appreciator'),
('Krishna Murthy', 28, 'India', 'Telugu', 'Nature lover'),
('Gopal Rao', 25, 'India', 'Telugu', 'Book collector'),
-- Gujarati
('Harsh Patel', 27, 'India', 'Gujarati', 'Business minded'),
('Darshan Shah', 25, 'India', 'Gujarati', 'Tech enthusiast'),
('Jayesh Mehta', 28, 'India', 'Gujarati', 'Music lover'),
('Ketan Desai', 26, 'India', 'Gujarati', 'Sports fan'),
('Chirag Joshi', 30, 'India', 'Gujarati', 'Travel enthusiast'),
('Parth Modi', 24, 'India', 'Gujarati', 'Food lover'),
('Yash Pandya', 29, 'India', 'Gujarati', 'Art collector'),
('Meet Thakkar', 26, 'India', 'Gujarati', 'Book reader'),
('Dev Raval', 28, 'India', 'Gujarati', 'Nature explorer'),
('Raj Bhatt', 25, 'India', 'Gujarati', 'Photography buff'),
-- Marathi
('Aditya Patil', 26, 'India', 'Marathi', 'Cricket lover'),
('Rohan Kulkarni', 28, 'India', 'Marathi', 'Tech professional'),
('Tejas Joshi', 25, 'India', 'Marathi', 'Music enthusiast'),
('Omkar Deshmukh', 27, 'India', 'Marathi', 'History buff'),
('Sagar Pawar', 30, 'India', 'Marathi', 'Travel lover'),
('Pratik More', 24, 'India', 'Marathi', 'Food explorer'),
('Nikhil Gaikwad', 29, 'India', 'Marathi', 'Art appreciator'),
('Akshay Jadhav', 26, 'India', 'Marathi', 'Book collector'),
('Varun Shinde', 28, 'India', 'Marathi', 'Sports fan'),
('Gaurav Thakur', 25, 'India', 'Marathi', 'Nature lover'),
-- Kannada
('Rakesh Gowda', 27, 'India', 'Kannada', 'Tech lover'),
('Sunil Shetty', 25, 'India', 'Kannada', 'Music fan'),
('Naveen Raj', 28, 'India', 'Kannada', 'Film buff'),
('Prashanth Kumar', 26, 'India', 'Kannada', 'Sports enthusiast'),
('Manjunath Reddy', 30, 'India', 'Kannada', 'Travel lover'),
('Harish Bhat', 24, 'India', 'Kannada', 'Food explorer'),
('Deepak Naik', 29, 'India', 'Kannada', 'Art collector'),
('Santosh Hegde', 26, 'India', 'Kannada', 'Book reader'),
('Vinay Rao', 28, 'India', 'Kannada', 'Nature explorer'),
('Kiran Murthy', 25, 'India', 'Kannada', 'Photography buff'),
-- Malayalam
('Vishnu Nair', 26, 'India', 'Malayalam', 'Film enthusiast'),
('Arun Menon', 28, 'India', 'Malayalam', 'Tech professional'),
('Sanjay Pillai', 25, 'India', 'Malayalam', 'Music lover'),
('Rahul Varma', 27, 'India', 'Malayalam', 'Sports fan'),
('Ajith Kumar', 30, 'India', 'Malayalam', 'Travel enthusiast'),
('Renjith Nair', 24, 'India', 'Malayalam', 'Food lover'),
('Anoop Krishnan', 29, 'India', 'Malayalam', 'Art collector'),
('Dileep Raj', 26, 'India', 'Malayalam', 'Book reader'),
('Jithin Thomas', 28, 'India', 'Malayalam', 'Nature explorer'),
('Vineeth Mohan', 25, 'India', 'Malayalam', 'Photography buff'),
-- Punjabi
('Gurpreet Singh', 27, 'India', 'Punjabi', 'Music lover'),
('Harjeet Kaur', 25, 'India', 'Punjabi', 'Dance enthusiast'),
('Manpreet Gill', 28, 'India', 'Punjabi', 'Sports fan'),
('Jaspreet Dhillon', 26, 'India', 'Punjabi', 'Travel lover'),
('Sukhbir Sandhu', 30, 'India', 'Punjabi', 'Food explorer'),
('Amritpal Mann', 24, 'India', 'Punjabi', 'History buff'),
('Davinder Sidhu', 29, 'India', 'Punjabi', 'Art appreciator'),
('Kulwant Brar', 26, 'India', 'Punjabi', 'Book collector'),
('Navjot Cheema', 28, 'India', 'Punjabi', 'Nature lover'),
('Parminder Bajwa', 25, 'India', 'Punjabi', 'Photography buff'),
-- Odia
('Subrat Panda', 26, 'India', 'Odia', 'Art lover'),
('Biswajit Mohanty', 28, 'India', 'Odia', 'Music enthusiast'),
('Prakash Sahu', 25, 'India', 'Odia', 'Sports fan'),
('Santosh Jena', 27, 'India', 'Odia', 'Travel lover'),
('Ashok Behera', 30, 'India', 'Odia', 'Food explorer'),
('Rajesh Nayak', 24, 'India', 'Odia', 'History buff'),
('Manoj Parida', 29, 'India', 'Odia', 'Book collector'),
('Suresh Patnaik', 26, 'India', 'Odia', 'Tech lover'),
('Gopi Mishra', 28, 'India', 'Odia', 'Nature explorer'),
('Ramesh Das', 25, 'India', 'Odia', 'Photography buff'),
-- English
('James Wilson', 27, 'USA', 'English', 'Tech professional'),
('Michael Brown', 25, 'UK', 'English', 'Music lover'),
('David Smith', 28, 'Australia', 'English', 'Sports enthusiast'),
('Chris Johnson', 26, 'Canada', 'English', 'Travel lover'),
('Robert Davis', 30, 'USA', 'English', 'Food explorer'),
('William Taylor', 24, 'UK', 'English', 'History buff'),
('Daniel Anderson', 29, 'Australia', 'English', 'Art collector'),
('Matthew Thomas', 26, 'Canada', 'English', 'Book reader'),
('Andrew Jackson', 28, 'USA', 'English', 'Nature explorer'),
('Ryan White', 25, 'UK', 'English', 'Photography buff'),
-- Spanish
('Carlos Garcia', 27, 'Spain', 'Spanish', 'Flamenco lover'),
('Miguel Rodriguez', 25, 'Mexico', 'Spanish', 'Music enthusiast'),
('Juan Martinez', 28, 'Argentina', 'Spanish', 'Football fan'),
('Pedro Lopez', 26, 'Spain', 'Spanish', 'Travel lover'),
('Luis Hernandez', 30, 'Mexico', 'Spanish', 'Food explorer'),
('Diego Gonzalez', 24, 'Argentina', 'Spanish', 'History buff'),
('Pablo Sanchez', 29, 'Spain', 'Spanish', 'Art collector'),
('Fernando Ramirez', 26, 'Mexico', 'Spanish', 'Book reader'),
('Alejandro Torres', 28, 'Argentina', 'Spanish', 'Nature explorer'),
('Javier Flores', 25, 'Spain', 'Spanish', 'Photography buff'),
-- French
('Pierre Dubois', 27, 'France', 'French', 'Wine enthusiast'),
('Jean Martin', 25, 'France', 'French', 'Art lover'),
('Marc Laurent', 28, 'France', 'French', 'Cinema buff'),
('Antoine Bernard', 26, 'Belgium', 'French', 'Travel lover'),
('Philippe Moreau', 30, 'France', 'French', 'Food explorer'),
('Olivier Petit', 24, 'Switzerland', 'French', 'History buff'),
('François Robert', 29, 'France', 'French', 'Music lover'),
('Nicolas Richard', 26, 'Belgium', 'French', 'Book reader'),
('Julien Durand', 28, 'France', 'French', 'Nature explorer'),
('Thomas Leroy', 25, 'France', 'French', 'Photography buff'),
-- Arabic
('Ahmed Hassan', 27, 'Egypt', 'Arabic', 'History lover'),
('Mohammed Ali', 25, 'UAE', 'Arabic', 'Tech enthusiast'),
('Omar Khalil', 28, 'Saudi Arabia', 'Arabic', 'Travel lover'),
('Youssef Ibrahim', 26, 'Egypt', 'Arabic', 'Music fan'),
('Karim Nasser', 30, 'Jordan', 'Arabic', 'Food explorer'),
('Hassan Mahmoud', 24, 'UAE', 'Arabic', 'Sports fan'),
('Tariq Ahmed', 29, 'Saudi Arabia', 'Arabic', 'Art collector'),
('Khalid Mansour', 26, 'Egypt', 'Arabic', 'Book reader'),
('Samir Farouk', 28, 'Jordan', 'Arabic', 'Nature explorer'),
('Walid Rashid', 25, 'UAE', 'Arabic', 'Photography buff'),
-- Chinese
('Wei Chen', 27, 'China', 'Chinese', 'Tech professional'),
('Li Wei', 25, 'China', 'Chinese', 'Music lover'),
('Zhang Ming', 28, 'China', 'Chinese', 'Calligraphy artist'),
('Wang Jun', 26, 'Taiwan', 'Chinese', 'Travel lover'),
('Liu Yang', 30, 'China', 'Chinese', 'Food explorer'),
('Huang Lei', 24, 'Singapore', 'Chinese', 'History buff'),
('Zhou Feng', 29, 'China', 'Chinese', 'Art collector'),
('Wu Tao', 26, 'Taiwan', 'Chinese', 'Book reader'),
('Xu Hao', 28, 'China', 'Chinese', 'Nature explorer'),
('Ma Cheng', 25, 'Singapore', 'Chinese', 'Photography buff'),
-- Urdu
('Imran Khan', 27, 'Pakistan', 'Urdu', 'Poetry lover'),
('Salman Ahmed', 25, 'Pakistan', 'Urdu', 'Music enthusiast'),
('Bilal Hussain', 28, 'India', 'Urdu', 'Literature fan'),
('Faisal Qureshi', 26, 'Pakistan', 'Urdu', 'Travel lover'),
('Asif Malik', 30, 'India', 'Urdu', 'Food explorer'),
('Kamran Ali', 24, 'Pakistan', 'Urdu', 'History buff'),
('Zeeshan Shah', 29, 'India', 'Urdu', 'Art collector'),
('Nadeem Raza', 26, 'Pakistan', 'Urdu', 'Book reader'),
('Shahid Mirza', 28, 'India', 'Urdu', 'Nature explorer'),
('Waqar Hassan', 25, 'Pakistan', 'Urdu', 'Photography buff');

-- Insert sample women for all major languages (10 per language)
INSERT INTO public.sample_women (name, age, country, language, bio) VALUES
-- Hindi
('Priya Sharma', 24, 'India', 'Hindi', 'Friendly and caring'),
('Ananya Singh', 26, 'India', 'Hindi', 'Love conversations'),
('Kavya Patel', 25, 'India', 'Hindi', 'Here to connect'),
('Riya Gupta', 28, 'India', 'Hindi', 'Enjoy meaningful talks'),
('Ishita Verma', 23, 'India', 'Hindi', 'Looking for friends'),
('Nisha Kumar', 27, 'India', 'Hindi', 'Music enthusiast'),
('Divya Joshi', 25, 'India', 'Hindi', 'Travel lover'),
('Sneha Rao', 24, 'India', 'Hindi', 'Tech professional'),
('Pooja Mishra', 26, 'India', 'Hindi', 'Art lover'),
('Shruti Reddy', 25, 'India', 'Hindi', 'Book reader'),
-- Bengali
('Aditi Das', 25, 'India', 'Bengali', 'Cultural enthusiast'),
('Shreya Banerjee', 27, 'India', 'Bengali', 'Poetry lover'),
('Ria Ghosh', 24, 'India', 'Bengali', 'Art appreciator'),
('Tanisha Sen', 26, 'India', 'Bengali', 'Music composer'),
('Moumita Bose', 28, 'India', 'Bengali', 'Writer at heart'),
('Pallavi Mukherjee', 23, 'India', 'Bengali', 'Film buff'),
('Sayantika Roy', 27, 'India', 'Bengali', 'History lover'),
('Ankita Chatterjee', 25, 'India', 'Bengali', 'Dance enthusiast'),
('Debjani Dey', 26, 'India', 'Bengali', 'Sports lover'),
('Rituparna Kar', 24, 'India', 'Bengali', 'Nature lover'),
-- Tamil
('Preethi Kumar', 26, 'India', 'Tamil', 'Tech professional'),
('Lavanya Rajan', 24, 'India', 'Tamil', 'Music lover'),
('Swetha Prakash', 27, 'India', 'Tamil', 'Film enthusiast'),
('Keerthana Anand', 25, 'India', 'Tamil', 'Classical dancer'),
('Soundarya Selvam', 28, 'India', 'Tamil', 'Travel enthusiast'),
('Divya Raja', 23, 'India', 'Tamil', 'Food lover'),
('Meena Venkat', 27, 'India', 'Tamil', 'Art collector'),
('Janani Murugan', 25, 'India', 'Tamil', 'Book reader'),
('Revathi Sundaram', 26, 'India', 'Tamil', 'Nature explorer'),
('Nithya Babu', 24, 'India', 'Tamil', 'Photography buff'),
-- Telugu
('Swathi Teja', 25, 'India', 'Telugu', 'Cinema enthusiast'),
('Anusha Rao', 27, 'India', 'Telugu', 'Tech lover'),
('Bhavana Reddy', 24, 'India', 'Telugu', 'Music fan'),
('Keerthi Kumar', 26, 'India', 'Telugu', 'Classical dancer'),
('Madhavi Varma', 28, 'India', 'Telugu', 'History buff'),
('Pavani Babu', 23, 'India', 'Telugu', 'Travel lover'),
('Ramya Chandra', 27, 'India', 'Telugu', 'Food explorer'),
('Sirisha Goud', 25, 'India', 'Telugu', 'Art appreciator'),
('Tejaswini Murthy', 26, 'India', 'Telugu', 'Nature lover'),
('Usha Rao', 24, 'India', 'Telugu', 'Book collector'),
-- Gujarati
('Hetal Patel', 26, 'India', 'Gujarati', 'Business minded'),
('Prachi Shah', 24, 'India', 'Gujarati', 'Tech enthusiast'),
('Riddhi Mehta', 27, 'India', 'Gujarati', 'Music lover'),
('Shivani Desai', 25, 'India', 'Gujarati', 'Garba dancer'),
('Tejal Joshi', 28, 'India', 'Gujarati', 'Travel enthusiast'),
('Urmi Modi', 23, 'India', 'Gujarati', 'Food lover'),
('Vaishali Pandya', 27, 'India', 'Gujarati', 'Art collector'),
('Zalak Thakkar', 25, 'India', 'Gujarati', 'Book reader'),
('Arti Raval', 26, 'India', 'Gujarati', 'Nature explorer'),
('Bhumi Bhatt', 24, 'India', 'Gujarati', 'Photography buff'),
-- Marathi
('Ashwini Patil', 25, 'India', 'Marathi', 'Lavani dancer'),
('Bhagyashree Kulkarni', 27, 'India', 'Marathi', 'Tech professional'),
('Chaitali Joshi', 24, 'India', 'Marathi', 'Music enthusiast'),
('Dipali Deshmukh', 26, 'India', 'Marathi', 'History buff'),
('Gauri Pawar', 28, 'India', 'Marathi', 'Travel lover'),
('Harshada More', 23, 'India', 'Marathi', 'Food explorer'),
('Isha Gaikwad', 27, 'India', 'Marathi', 'Art appreciator'),
('Janhavi Jadhav', 25, 'India', 'Marathi', 'Book collector'),
('Ketaki Shinde', 26, 'India', 'Marathi', 'Sports fan'),
('Leena Thakur', 24, 'India', 'Marathi', 'Nature lover'),
-- Kannada
('Akshata Gowda', 26, 'India', 'Kannada', 'Tech lover'),
('Bhavya Shetty', 24, 'India', 'Kannada', 'Music fan'),
('Chaitra Raj', 27, 'India', 'Kannada', 'Film buff'),
('Divya Kumar', 25, 'India', 'Kannada', 'Classical dancer'),
('Geetha Reddy', 28, 'India', 'Kannada', 'Travel lover'),
('Harini Bhat', 23, 'India', 'Kannada', 'Food explorer'),
('Ishwarya Naik', 27, 'India', 'Kannada', 'Art collector'),
('Jyothi Hegde', 25, 'India', 'Kannada', 'Book reader'),
('Kavitha Rao', 26, 'India', 'Kannada', 'Nature explorer'),
('Lakshmi Murthy', 24, 'India', 'Kannada', 'Photography buff'),
-- Malayalam
('Anjali Nair', 25, 'India', 'Malayalam', 'Film enthusiast'),
('Bhavana Menon', 27, 'India', 'Malayalam', 'Tech professional'),
('Chandana Pillai', 24, 'India', 'Malayalam', 'Music lover'),
('Deepa Varma', 26, 'India', 'Malayalam', 'Bharatanatyam dancer'),
('Fathima Kumar', 28, 'India', 'Malayalam', 'Travel enthusiast'),
('Gayathri Nair', 23, 'India', 'Malayalam', 'Food lover'),
('Hema Krishnan', 27, 'India', 'Malayalam', 'Art collector'),
('Indira Raj', 25, 'India', 'Malayalam', 'Book reader'),
('Jayasree Thomas', 26, 'India', 'Malayalam', 'Nature explorer'),
('Karthika Mohan', 24, 'India', 'Malayalam', 'Photography buff'),
-- Punjabi
('Simran Kaur', 26, 'India', 'Punjabi', 'Bhangra dancer'),
('Harpreet Singh', 24, 'India', 'Punjabi', 'Music enthusiast'),
('Jasleen Gill', 27, 'India', 'Punjabi', 'Food lover'),
('Kirandeep Dhillon', 25, 'India', 'Punjabi', 'Travel lover'),
('Manmeet Sandhu', 28, 'India', 'Punjabi', 'Sports fan'),
('Navneet Mann', 23, 'India', 'Punjabi', 'History buff'),
('Prabhjot Sidhu', 27, 'India', 'Punjabi', 'Art appreciator'),
('Rajinder Brar', 25, 'India', 'Punjabi', 'Book collector'),
('Sukhleen Cheema', 26, 'India', 'Punjabi', 'Nature lover'),
('Tanjeet Bajwa', 24, 'India', 'Punjabi', 'Photography buff'),
-- Odia
('Anita Panda', 25, 'India', 'Odia', 'Classical dancer'),
('Barsha Mohanty', 27, 'India', 'Odia', 'Music enthusiast'),
('Chandini Sahu', 24, 'India', 'Odia', 'Art lover'),
('Deepika Jena', 26, 'India', 'Odia', 'Travel lover'),
('Gitanjali Behera', 28, 'India', 'Odia', 'Food explorer'),
('Hemanti Nayak', 23, 'India', 'Odia', 'History buff'),
('Itishree Parida', 27, 'India', 'Odia', 'Book collector'),
('Jyoti Patnaik', 25, 'India', 'Odia', 'Tech lover'),
('Kalpana Mishra', 26, 'India', 'Odia', 'Nature explorer'),
('Laxmi Das', 24, 'India', 'Odia', 'Photography buff'),
-- English
('Emily Wilson', 26, 'USA', 'English', 'Tech professional'),
('Sarah Brown', 24, 'UK', 'English', 'Music lover'),
('Jessica Smith', 27, 'Australia', 'English', 'Travel enthusiast'),
('Ashley Johnson', 25, 'Canada', 'English', 'Food blogger'),
('Amanda Davis', 28, 'USA', 'English', 'Art collector'),
('Brittany Taylor', 23, 'UK', 'English', 'History buff'),
('Chelsea Anderson', 27, 'Australia', 'English', 'Book reader'),
('Diana Thomas', 25, 'Canada', 'English', 'Nature explorer'),
('Elizabeth Jackson', 26, 'USA', 'English', 'Photography buff'),
('Fiona White', 24, 'UK', 'English', 'Film enthusiast'),
-- Spanish
('Maria Garcia', 26, 'Spain', 'Spanish', 'Flamenco dancer'),
('Sofia Rodriguez', 24, 'Mexico', 'Spanish', 'Music lover'),
('Isabella Martinez', 27, 'Argentina', 'Spanish', 'Tango dancer'),
('Lucia Lopez', 25, 'Spain', 'Spanish', 'Travel enthusiast'),
('Valentina Hernandez', 28, 'Mexico', 'Spanish', 'Food explorer'),
('Camila Gonzalez', 23, 'Argentina', 'Spanish', 'History buff'),
('Elena Sanchez', 27, 'Spain', 'Spanish', 'Art collector'),
('Paula Ramirez', 25, 'Mexico', 'Spanish', 'Book reader'),
('Andrea Torres', 26, 'Argentina', 'Spanish', 'Nature explorer'),
('Laura Flores', 24, 'Spain', 'Spanish', 'Photography buff'),
-- French
('Marie Dubois', 26, 'France', 'French', 'Fashion lover'),
('Sophie Martin', 24, 'France', 'French', 'Art enthusiast'),
('Julie Laurent', 27, 'France', 'French', 'Cinema buff'),
('Camille Bernard', 25, 'Belgium', 'French', 'Travel lover'),
('Léa Moreau', 28, 'France', 'French', 'Food explorer'),
('Emma Petit', 23, 'Switzerland', 'French', 'History buff'),
('Chloé Robert', 27, 'France', 'French', 'Music lover'),
('Manon Richard', 25, 'Belgium', 'French', 'Book reader'),
('Inès Durand', 26, 'France', 'French', 'Nature explorer'),
('Louise Leroy', 24, 'France', 'French', 'Photography buff'),
-- Arabic
('Fatima Hassan', 26, 'Egypt', 'Arabic', 'History lover'),
('Aisha Ali', 24, 'UAE', 'Arabic', 'Fashion enthusiast'),
('Mariam Khalil', 27, 'Saudi Arabia', 'Arabic', 'Travel lover'),
('Noor Ibrahim', 25, 'Egypt', 'Arabic', 'Music fan'),
('Sara Nasser', 28, 'Jordan', 'Arabic', 'Food explorer'),
('Layla Mahmoud', 23, 'UAE', 'Arabic', 'Art collector'),
('Huda Ahmed', 27, 'Saudi Arabia', 'Arabic', 'Book reader'),
('Rania Mansour', 25, 'Egypt', 'Arabic', 'Nature lover'),
('Yasmin Farouk', 26, 'Jordan', 'Arabic', 'Photography buff'),
('Zainab Rashid', 24, 'UAE', 'Arabic', 'Dance enthusiast'),
-- Chinese
('Li Na', 26, 'China', 'Chinese', 'Tech professional'),
('Wang Fang', 24, 'China', 'Chinese', 'Music lover'),
('Zhang Mei', 27, 'China', 'Chinese', 'Calligraphy artist'),
('Chen Ying', 25, 'Taiwan', 'Chinese', 'Travel lover'),
('Liu Xia', 28, 'China', 'Chinese', 'Food explorer'),
('Huang Yan', 23, 'Singapore', 'Chinese', 'History buff'),
('Zhou Lin', 27, 'China', 'Chinese', 'Art collector'),
('Wu Jing', 25, 'Taiwan', 'Chinese', 'Book reader'),
('Xu Hui', 26, 'China', 'Chinese', 'Nature explorer'),
('Ma Li', 24, 'Singapore', 'Chinese', 'Photography buff'),
-- Urdu
('Fatima Khan', 26, 'Pakistan', 'Urdu', 'Poetry lover'),
('Ayesha Ahmed', 24, 'Pakistan', 'Urdu', 'Music enthusiast'),
('Sana Hussain', 27, 'India', 'Urdu', 'Literature fan'),
('Zara Qureshi', 25, 'Pakistan', 'Urdu', 'Travel lover'),
('Hina Malik', 28, 'India', 'Urdu', 'Food explorer'),
('Maira Ali', 23, 'Pakistan', 'Urdu', 'History buff'),
('Nadia Shah', 27, 'India', 'Urdu', 'Art collector'),
('Rabia Raza', 25, 'Pakistan', 'Urdu', 'Book reader'),
('Saima Mirza', 26, 'India', 'Urdu', 'Nature explorer'),
('Tania Hassan', 24, 'Pakistan', 'Urdu', 'Photography buff');