ALTER TABLE public.women_kyc 
ADD COLUMN IF NOT EXISTS fathers_name text,
ADD COLUMN IF NOT EXISTS mothers_name text,
ADD COLUMN IF NOT EXISTS marital_status text,
ADD COLUMN IF NOT EXISTS nationality text DEFAULT 'Indian',
ADD COLUMN IF NOT EXISTS occupation text,
ADD COLUMN IF NOT EXISTS annual_income_range text,
ADD COLUMN IF NOT EXISTS mobile_number text,
ADD COLUMN IF NOT EXISTS email_address text,
ADD COLUMN IF NOT EXISTS current_address text,
ADD COLUMN IF NOT EXISTS permanent_address text,
ADD COLUMN IF NOT EXISTS city text,
ADD COLUMN IF NOT EXISTS state text,
ADD COLUMN IF NOT EXISTS pin_code text,
ADD COLUMN IF NOT EXISTS address_proof_type text,
ADD COLUMN IF NOT EXISTS address_proof_url text,
ADD COLUMN IF NOT EXISTS bank_branch_name text,
ADD COLUMN IF NOT EXISTS account_type text DEFAULT 'savings',
ADD COLUMN IF NOT EXISTS nominee_name text,
ADD COLUMN IF NOT EXISTS nominee_relationship text,
ADD COLUMN IF NOT EXISTS nominee_dob text,
ADD COLUMN IF NOT EXISTS nominee_address text,
ADD COLUMN IF NOT EXISTS declaration_place text;