// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Fallbacks for self-hosted builds
// MUST set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY at build time
// to override these defaults.
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Track whether Supabase is properly configured
export const isSupabaseConfigured = !!(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!isSupabaseConfigured) {
  console.error(
    'Missing required environment variables: VITE_SUPABASE_URL and/or VITE_SUPABASE_PUBLISHABLE_KEY. ' +
    'The app will render a configuration error screen.'
  );
}

// Safe localStorage wrapper — handles private browsing, iOS WKWebView, and sandboxed contexts
const safeStorage = {
  getItem: (key: string): string | null => {
    try {
      return localStorage.getItem(key);
    } catch {
      return null;
    }
  },
  setItem: (key: string, value: string): void => {
    try {
      localStorage.setItem(key, value);
    } catch {
      // Silently fail — in-memory session only
    }
  },
  removeItem: (key: string): void => {
    try {
      localStorage.removeItem(key);
    } catch {
      // Silently fail
    }
  },
};

// Dummy no-op client for when env vars are missing (prevents hard crash)
const dummyClient = {
  auth: {
    onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
    getSession: () => Promise.resolve({ data: { session: null }, error: null }),
    getUser: () => Promise.resolve({ data: { user: null }, error: null }),
    signInWithPassword: () => Promise.reject(new Error('Supabase not configured')),
    signUp: () => Promise.reject(new Error('Supabase not configured')),
    signOut: () => Promise.resolve({ error: null }),
    resetPasswordForEmail: () => Promise.reject(new Error('Supabase not configured')),
    updateUser: () => Promise.reject(new Error('Supabase not configured')),
  },
  from: () => ({
    select: () => ({ eq: () => ({ maybeSingle: () => Promise.resolve({ data: null, error: new Error('Supabase not configured') }), single: () => Promise.resolve({ data: null, error: new Error('Supabase not configured') }) }), data: null, error: new Error('Supabase not configured') }),
    insert: () => Promise.reject(new Error('Supabase not configured')),
    update: () => Promise.reject(new Error('Supabase not configured')),
    delete: () => Promise.reject(new Error('Supabase not configured')),
    upsert: () => Promise.reject(new Error('Supabase not configured')),
  }),
  storage: { from: () => ({ upload: () => Promise.reject(new Error('Supabase not configured')), getPublicUrl: () => ({ data: { publicUrl: '' } }) }) },
  channel: () => ({ on: () => ({ subscribe: () => ({}) }), subscribe: () => ({}), unsubscribe: () => {} }),
  removeChannel: () => {},
  functions: { invoke: () => Promise.reject(new Error('Supabase not configured')) },
} as any;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: safeStorage,
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
        flowType: 'pkce',
      },
      db: {
        schema: 'public',
      },
      global: {
        headers: {
          'x-client-info': 'meow-app/1.0',
        },
      },
      realtime: {
        params: {
          eventsPerSecond: 40,
        },
      },
    })
  : dummyClient;

/** In-memory session only. Never hits GET /auth/v1/user (403 on expired JWTs). */
export async function getLocalAuthUser(): Promise<{ id: string; email?: string } | null> {
  try {
    const { data: { session } } = await supabase.auth.getSession();
    const user = session?.user;
    return user ? { id: user.id, email: user.email } : null;
  } catch {
    return null;
  }
}
